version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: fastbreak
      POSTGRES_PASSWORD: Dev@123!
      POSTGRES_DB: myQ
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://fastbreak:Dev@123!@postgres:5432/myQ
      - JWT_SECRET=${JWT_SECRET}
      - APP_URL=http://localhost:3000
      - PORT=3001
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres-data:
